### ISSUE TITLE
Configuration UI

### ISSUE THREAD

**Issue by srguglielmo** [srguglielmo/SimpleShib#3]
Look into a UI for the configuration. Useful for shared hosting/etc.

See #1.

**Comment by tthorp** [comment]
I would like to weigh in on this. I agree that implementers of this plugin will be a highly technical crowd and don't think the user interface is entirely necessary as the settings are only used on initial setup. 

However, the way it is currently structured, any plugin updates will wipe out the configuration. Can I suggest the following for your distribution?

simpleshib.php (has a php include of shib-settings.php)
shib-settings-sample.php

This would follow the setup of wp-config.php/wp-config-sample.php

**Comment by srguglielmo** [comment]
Small follow up here: Moving the configuration into WordPress's Settings API is being done on branch `settings_api`. I expect to have a release within a week.

**Comment by srguglielmo** [comment]
This was merged into master and version 1.2.0 tagged. I'll push to wordpress.org once I perform some more in-depth testing. Again, should be within a few days or a week at most.

**Comment by srguglielmo** [comment]
This has been released with version 1.2.0 and pushed to wordpress.org.
