### ISSUE TITLE
confusion on setup comment

### ISSUE THREAD

**Issue by tthorp** [srguglielmo/SimpleShib#4]
Thanks for the plugin. I like the idea but it is not working for me yet. I thought I would start my troubleshooting by ironing out a little confusion.

"Set to true to disable all login functionality."
do you mean
"Set to true to disable native Wordpress login functionality"
or 
"Set to true to disable Shibboleth SSO"
or ...

**Comment by tthorp** [comment]
disregard. it makes sense if the plugin is installed correctly. 
I mistakenly uploaded the plugin directory to mu-plugins instead of the file, so the whole plugin was not being processed by wordpress.

**Comment by srguglielmo** [comment]
Hi @tthorp,

Thanks for the ticket/feedback. That boolean is to disable **all** login functionality, both native WP and through Shib. The code first calls `remove_all_filters('authenticate')` in the construct, which removes everything related to authentication. Then, it adds `authenticate_or_redirect()` which becomes the only function for authentication in WordPress. That function checks if `LoginsDisabled` is true, and if so, just returns an error. It essentially prevents all logins from anywhere.

I initially used it as a debugging/testing type thing, but ended up keeping it in the settings just in case someone would need it. I can definitely clarify the wording in the comments though (I'll reopen this ticket until I can do that, so I won't forget). That should help any future confusion.

Thanks again for the feedback and let me know if you have any issues using the plugin!

Thanks,
Steve

**Comment by srguglielmo** [comment]
Fixed in 33f1458c8b722bae88a23c128d7bc734c1fac60a
